# Generated by Django 3.1.14 on 2023-03-16 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0002_auto_20230316_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonentity',
            name='Attack',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='Defense',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='Health',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='Level',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='Stamina',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
